require("plugins-config.autopairs")
require("plugins-config.bufferline")
require("plugins-config.comment")
require("plugins-config.dashboard")
require("plugins-config.gitsigns")
-- require("plugins-config.indent-blankline")
require("plugins-config.lualine")
require("plugins-config.nvim-tree")
require("plugins-config.onedark")
require("plugins-config.projects")
require("plugins-config.telescope")
require("plugins-config.toggleterm")
require("plugins-config.treesitter")
require("plugins-config.which-key")
